server:
  port: 80
spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/mysql?useUnicode=true&characterEncoding=UTF-8
     username: root
     password: a15945435723
     driverClassName: com.mysql.jdbc.Driver
     type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
     mode: HTML5
     cache: false

##驼峰命名
mybatis:
  type-aliases-package: shop4j.models
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

mapper:
  mappers: shop4j.dao.BaseMapper
  not-empty: false
  identity: MYSQL

##商品图片地址 目标和链接
images:
  handler: /image/**
  location: D:/images/,/opt/images/






