server:
  port: 80
spring:
  datasource:
     url: jdbc:mysql://rds1d57s9y9ez81im192o.mysql.rds.aliyuncs.com:3306/shopcar?zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
     username: huimin0328
     password: cqLanRUbChX6
     driverClassName: com.mysql.jdbc.Driver
     type: com.alibaba.druid.pool.DruidDataSource
     # 下面为连接池的补充设置，应用到上面所有数据源中


#mybatis&&通用Mapper
mybatis:
  type-aliases-package: shop4j.model
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers: shop4j.dao.BaseMapper
  not-empty: false
  identity: MYSQL





